name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.2.1
